main/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.home, name = 'home'),
    path('all_news', views.all_news, name = 'all-news'),
    path('detail/<int:id>', views.detail, name ='detail'),
    path('accounts/register/', views.register, name = 'register'),
    path('create', views.create_news, name ='create'),
    path('edit/<int:id>', views.edit, name ='edit'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

news/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
# from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length = 200)
    category_image = models.ImageField(upload_to = 'imgs/')

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title

class News(models.Model):
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    title = models.CharField(max_length = 300)
    image = models.ImageField(upload_to = 'imgs/')
    detail = models.TextField()
    add_time = models.DateTimeField(auto_now_add = True)
    privacy = models.BooleanField(default = False)

    class Meta:
        verbose_name_plural = 'News'

    def __str__(self):
        return self.title

class Comment(models.Model):
    news = models.ForeignKey(News, on_delete = models.CASCADE)
    name = models.CharField(max_length = 100)
    email = models.CharField(max_length = 200)
    comment = models.TextField()
    status = models.BooleanField(default = False)

    def __str__(self):
        return self.comment

main/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserCreationForm
from .models import News, Category


# Create your views here.
def home(request):
    first_news = News.objects.first()
    three_news = News.objects.all()[1:3]
    categories = Category.objects.all()

    return render(request, 'home.html',{
        'first_news': first_news,
        'three_news': three_news,
        'categories': categories,
    })


def all_news(request):
    all_news = News.objects.all()
    return render(request,'all-news.html',{
        'all_news': all_news
    })

def create_news(request):
    if request.method == 'POST':
        title = request.POST['title']
        image = request.POST['image']
        detail = request.POST['detail']
        category = request.POST['category']
        cat = Category.objects.get(title = category)
        cat_id = cat.id
        privacy = request.POST['privacy']
        if privacy == "true" or "True":
            privacy_bool = 1

        News.objects.create(
            title = title,
            image = image,
            detail = detail,
            category_id = cat_id,
            privacy = privacy_bool
        )
        messages.success(request, 'Saved')
    return render(request,'create_news.html')

def edit(request, id):
    news = News.objects.get(pk = id)
    if request.method == 'POST':
        title = request.POST['title']
        image = request.POST['image']
        detail = request.POST['detail']
        category = request.POST['category']
        cat = Category.objects.get(title = category)
        cat_id = cat.id
        privacy = request.POST['privacy']
        if privacy == "true" or "True":
            privacy_bool = 1

        news.title = title
        news.image = image
        news.detail = detail
        news.category_id = cat_id
        news.privacy = privacy_bool
        news.save()


        messages.success(request, 'Saved')

    return render(request,'edit_news.html',{
        'news': news
    })

def detail(request, id):
    news = News.objects.get(pk = id)
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        comment = request.POST['message']
        Comment.objects.create(
            news = news,
            name = name,
            email = email,
            comment = comment
        )
        messages.success(request, 'Comment submitted but in moderation mode')

    category = Category.objects.get(id = news.category.id)
    rel_news = News.objects.filter(category = category).exclude(id = id)
    return render(request,'detail.html',{
        'news': news,
        'related_news': rel_news
    })


#User Registration
def register(request):
    form = UserCreationForm
    if request.method == 'POST':
        regForm = UserCreationForm(request.POST)
        if regForm.is_valid():
            regForm.save()
            messages.success(request, 'User has been successfully registered')
    return render(request, 'registration/register.html',{
        'form': form
    })

main/templates/all-news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
	<h3 class="border-bottom pb-1 my-4">All News</h3>
    <!-- News Box -->
    {% for news in all_news %}
	<div class="card mb-4 shadow">
	  <div class="row no-gutters">
	    <div class="col-md-3">
            <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title">{{news.title}}</h5>
	        <p class="card-text">{{news.detail}}</p>
	        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
	      </div>
	    </div>
	  </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

main/templates/base.html
{% load static %}
{% load auth_extras %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Home Page{% endblock %}</title>
	<!-- Bootstrap 4 CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bs4/bootstrap.min.css' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'vendor/jquery.min.js' %}"></script>
	<!-- Bootstrap Js -->
	<script type="text/javascript" src="{% static '/vendor/bs4/bootstrap.min.js' %}"></script>
</head>
<body>
	<!-- Top News -->
	<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
		<div class="container">
		  <a class="navbar-brand" href="/">The Daily Bugle</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item active">
		        <a class="nav-link" href="/">Home</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'all-news' %}">All News</a>
		      </li>
          {% if user.is_authenticated %}
          {% if request.user|has_group:"Editors" %}
          <li class="nav-item">
		        <a class="nav-link" href="{% url 'create' %}">Create News</a>
		      </li>
          {% endif %}
          <li class="nav-item">
		        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
		      </li>
          {% else %}
          <li class="nav-item">
		        <a class="nav-link" href="{% url 'login' %}">Log In</a>
		      </li>
          <li class="nav-item">
		        <a class="nav-link" href="{% url 'register' %}">Register</a>
		      </li>
          {% endif %}
		    </ul>
		  </div>
	  	</div>
    </nav>

    {% block content %}
    {% endblock %}

<hr/>
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
  </div>
</footer>
</body>
</html>

main/templates/create_news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
<div class="card my-4">
  <h6 class="card-header">Add News Page</h6>
  <div class="card-body">
    {% for message in messages %}
    <p class="text-success">{{message}}</p>
    {% endfor %}
    <form method="post" action="create">
      {% csrf_token %}
      <div class="form-group row">
        <label class="col-md-2">Title<span class="text-danger">*</span></label>
        <div class="col-md-10">
          <input type="text" name="title" required class="form-control" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-2">Image<span class="text-danger">*</span></label>
        <div class="col-md-10">
          <input type="file" name="image" required class="form-control" accept="image/*" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-2">Details<span class="text-danger">*</span></label>
        <div class="col-md-10">
          <textarea class="form-control" name="detail" required></textarea>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-2">Category<span class="text-danger">*</span></label>
        <div class="col-md-10">
          <input type="text" name="category" required class="form-control" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-2">Privacy<span class="text-danger">*</span></label>
        <div class="col-md-10">
          <input type="text" name="privacy" required class="form-control" />
        </div>
      </div>
      <input type="submit" class="btn btn-primary" />
    </form>
  </div>
</div>
</main>
{% endblock %}

main/templates/detail.html
{% extends 'base.html' %}
{% load auth_extras %}
{% load static %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->

		<div class="col-md-8">
			<div class="card mb-3">
        <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/>
			    <p class="card-text">{{news.detail}}</p>
			  </div>
        {% if request.user|has_group:"Editors" %}
        <div class="card-footer">
			  	<a href="/edit/{{news.id}}">Edit this publication</a>
			  </div>
        {% endif %}
			</div>

			<!-- Comments -->
			<div class="card my-4">
				<h6 class="card-header">Add Comment</h6>
				<div class="card-body">
					{% for message in messages %}
					<p class="text-success">{{message}}</p>
					{% endfor %}
					<form method="post" action="/detail/{{news.id}}">
						{% csrf_token %}
						<div class="form-group row">
							<label class="col-md-2">Name<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="text" name="name" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">Email<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<input type="temailext" name="email" required class="form-control" />
							</div>
						</div>
						<div class="form-group row">
							<label class="col-md-2">Comment<span class="text-danger">*</span></label>
							<div class="col-md-10">
								<textarea class="form-control" name="message" required></textarea>
							</div>
						</div>
						<input type="submit" class="btn btn-primary" />
					</form>
				</div>
			</div>
			<!-- Previous Comments -->
			<div class="card my-4">
				<h6 class="card-header">Comments</h6>
				<div class="card-body">
					{% for comment in comments %}
					<blockquote class="blockquote text-right">
					  <p class="mb-0">{{comment.comment}}</p>
					  <footer class="blockquote-footer">{{comment.name}} <cite title="Source Title">{{comment.email}}</cite></footer>
					</blockquote>
					<hr/>
					{% endfor %}
				</div>
			</div>
		</div>
		<!-- Related News -->
		<div class="col-md-4">
			<h3 class="mb-3 border-bottom pb-1">From this Category</h3>
			<!-- Category Box -->
			{% for news in related_news %}
			<div class="card mb-3 shadow">
                <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{news.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			  </div>
			</div>
			{% endfor %}
		</div>
	</div>
</main>
{% endblock %}

main/templates/edit_news.html
{% extends 'base.html' %}
{% block content %}
<main class="container mt-3 mb-5">
<div class="card my-4">
  <h6 class="card-header">Edit the Publication</h6>
  <div class="card-body">
    {% for message in messages %}
    <p class="text-success">{{message}}</p>
    {% endfor %}
    <form method="post" action="/edit/{{news.id}}">
      {% csrf_token %}
      <div class="form-group row">
        <label class="col-md-2">Title<span class="text-danger">*</span></label>
        <div class="col-md-10">
          <input type="text" name="title" required class="form-control" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-2">Image<span class="text-danger">*</span></label>
        <div class="col-md-10">
          <input type="file" name="image" required class="form-control" accept="image/*" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-2">Details<span class="text-danger">*</span></label>
        <div class="col-md-10">
          <textarea class="form-control" name="detail" required></textarea>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-2">Category<span class="text-danger">*</span></label>
        <div class="col-md-10">
          <input type="text" name="category" required class="form-control" />
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-2">Privacy<span class="text-danger">*</span></label>
        <div class="col-md-10">
          <input type="text" name="privacy" required class="form-control" />
        </div>
      </div>
      <input type="submit" class="btn btn-primary" />
    </form>
  </div>
</div>
</main>
{% endblock %}

main/templates/home.html
{% extends 'base.html' %}
{% load auth_extras %}
{% block content %}
<main class="container mt-3 mb-5">
	<!-- featured news -->
	<div class="row my-3">
		<!-- Left -->
		<div class="col-md-7">
			<div class="card mb-3">
			  <img src="/media/{{first_news.image}}" class="card-img-top" alt="{{first_news.title}}">
			  <div class="card-body">
			    <h5 class="card-title">{{first_news.title}}</h5>
			    <hr/>
			    <p class="card-text"><a href="/detail/{{first_news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			  </div>
			</div>
		</div>
		<!-- Right -->
		<div class="col-md-5" style="max-height: 450px; overflow: auto;">
			{% for news in three_news %}
			<!-- News Box -->
			<div class="card">
			  <div class="row no-gutters">
			    <div class="col-md-4">
					<img src="media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
			    </div>
			    <div class="col-md-8">
			      <div class="card-body">
			        <h5 class="card-title">{{news.title}}</h5>
			        <p class="card-text"><a href="/detail/{{news.id}}" class="btn btn-sm btn-primary">Read Full</a></p>
			      </div>
			    </div>
			  </div>
			</div>
			<hr/>
			{% endfor %}
		</div>
	</div>
	<!-- Category Wise News -->
	{% for category in categories %}
	<h3 class="border-bottom pb-1">{{category.title}}</h3>
	<div class="row my-4">
		{% for news in category.news_set.all %}
			{% if forloop.counter < 5 %}
        {% if news.privacy == 0 %}
			<!-- News box -->
			<div class="col-md-3">
				<div class="card mb-3 shadow">
				<img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<hr/>
					<p class="card-text"><a href="#" class="btn btn-sm btn-primary">Read Full</a></p>
				</div>
				</div>
			</div>
          {% endif %}
        {% endif %}
		{% endfor %}
	</div>
	{% endfor %}
	<!-- End Single Category -->

  {% if request.user|has_group:"Subscribers" %}
	<h3 class="border-bottom pb-1">Private News</h3>
  {% for category in categories %}
	<div class="row my-4">
		{% for news in category.news_set.all %}
			{% if forloop.counter < 5 %}
        {% if news.privacy == 1 %}
			<!-- News box -->
			<div class="col-md-3">
				<div class="card mb-3 shadow">
				<img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
				<div class="card-body">
					<h5 class="card-title">{{news.title}}</h5>
					<hr/>
					<p class="card-text"><a href="#" class="btn btn-sm btn-primary">Read Full</a></p>
				</div>
				</div>
			</div>
        {% endif %}
      {% endif %}
		{% endfor %}
	</div>
	{% endfor %}
  {% endif %}

  {% if request.user|has_group:"Editors" %}
  <h3 class="border-bottom pb-1">Private News</h3>
  {% for category in categories %}
  <div class="row my-4">
    {% for news in category.news_set.all %}
      {% if forloop.counter < 5 %}
        {% if news.privacy == 1 %}
      <!-- News box -->
      <div class="col-md-3">
        <div class="card mb-3 shadow">
        <img src="/media/{{news.image}}" class="card-img-top" alt="{{news.title}}">
        <div class="card-body">
          <h5 class="card-title">{{news.title}}</h5>
          <hr/>
          <p class="card-text"><a href="#" class="btn btn-sm btn-primary">Read Full</a></p>
        </div>
        </div>
      </div>
        {% endif %}
      {% endif %}
    {% endfor %}
  </div>
  {% endfor %}
  {% endif %}
</main>
{% endblock %}